/**
 * Scripted opening line — the simulated customer's first words, authored per
 * scenario (`script.openingLine`) instead of generated by a model call.
 *
 * Why (plan W2.8 · G804 · Factory#5238): the opener is the most repetitive turn
 * in every session — same scenario, same persona, same first sentence — and on
 * the phone path it is the gap a trainee waits through in silence after
 * answering. An authored line costs zero model calls and zero generation
 * latency, and it lets the scenario author fix exactly how the customer opens.
 * A scenario without one keeps the existing model-generated opener.
 *
 * Pure and Worker-safe: no I/O, no Node built-ins.
 */

/**
 * `chat_messages.model` stamped on a scripted opener, so latency analytics
 * (R-066/R-068 `byModel`) group it apart from real model turns instead of
 * crediting a 0 ms turn to a model that never ran.
 */
export const SCRIPTED_OPENING_MODEL = 'scripted';

/** `chat_messages.route_reason` stamped on a scripted opener. */
export const SCRIPTED_OPENING_ROUTE_REASON = 'scripted-opening';

/**
 * The scenario's authored opening line, trimmed — or `null` when the script has
 * none (missing, not a string, or blank), meaning the caller should fall back
 * to generating the opener with the model.
 *
 * @param script Raw scenario `script` JSON from the DB (any shape, may be null).
 */
export function scriptedOpeningLine(script: unknown): string | null {
  if (!script || typeof script !== 'object') return null;
  const line = (script as { openingLine?: unknown }).openingLine;
  if (typeof line !== 'string') return null;
  const trimmed = line.trim();
  return trimmed.length > 0 ? trimmed : null;
}
